services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    container_name: teamtasks-mysql
    environment:
      MYSQL_DATABASE: teamtasks
      MYSQL_USER: teamtasks
      MYSQL_PASSWORD: teamtasks-password
      MYSQL_ROOT_PASSWORD: teamtasks-root-password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: